### PR TITLE
Add computation of gradients for Likelihood and Posterior

### PR DESCRIPTION
**Pull request by mirca**
This PR computes gradients for Likelihoods and Posteriors. The tests verify that the gradient is close to 0 at the solution.

cc @barentsen

### CODE REVIEW

**Comment by barentsen** [comment]
I've never used gradients in Python so I don't have much background on this, but it looks OK to me!

**Comment by mirca** [comment]
I will add more tests for analytical cases to make sure we're doing it right!

**Comment by barentsen** [comment]
If you have questions, e.g. about why using the gradients in scipy.optimize is slower, or how to get a gradient for a scipy.interpolate function, I'd encourage you to isolate the issue in an as-simple-as-possible gist that demoes the issue, and then open a scipy issue and tweet it!

**Comment by mirca** [comment]
@barentsen I think this is correct. I wrote tests against analytical gradients and everything is green. Are you happy for me to merge this? :)

**Comment by barentsen** [comment]
Yes, let's merge so we can start figuring out if gradients can help us WIN!

**Pull request merged**
