### PR TITLE
Add a Probability Density Function abstract base class

### PR DESCRIPTION
**Pull request by barentsen**
Just playing around: what do you think about this @mirca?

### CODE REVIEW

**Comment by mirca** [comment]
That's awesome, I like it! =D

**Comment by barentsen** [comment]
My proposal is crap because if you do
```
a = Uniform(0, 1)
b = Uniform(0, 1)
c = a * b
```
then there is no way to evaluate `a.lnlike(x1) + b.lnlike(x2)` using `c.lnlike()`, because it will only accept `c.lnlike(x1)` or `c.lnlike(x2)`.

**Comment by mirca** [comment]
Then we should think of a fancier ``CompositePDF``?

**Comment by barentsen** [comment]
I think `pymc3` solves this by having you set the data when you define the distribution, e.g. you do
```
a = pymc3.Uniform('a', lower=0, upper=1, observed=x1)
b = pymc3.Uniform('b', lower=0, upper=1, observed=x2)
```

If you were to think very carefully about `octopus` for five years, I think what you would end up with is `pymc3`.

**Comment by barentsen** [comment]
We can close this PR for now and reconsider the Ultimate Design (tm) for oktopus at a later date, when we fully understand all the features and use-cases!

**Pull request closed without merging**
